Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y python3 python3-pip python3-yaml git build-essential cmake gcc-arm-none-eabi
     pip3 install --upgrade pip3
     pip3 install kittyfuzzer pyusb pyserial
     git clone https://github.com/bkerler/Facedancer --recursive
     cd Facedancer
     cd MTP
     python3 setup.py install
     cd ..
     cd greatfet/host
     python3 setup.py install
     cd ..
     git submodule init
     git submodule update
     cd firmware/libopencm3
     make
     cd ..
     cd greatfet_usb
     mkdir build
     cd build
     cmake .. -DBOARD=GREATFET_ONE
     make
     cd ~
  SHELL
end
